apiVersion: v1
data:
  MARIADB_ROOT_PASSWORD: c2VjcmV0Cg== # secret
  MARIADB_USER: dXNlcgo= # user
  MARIADB_PASSWORD: cGFzc3dvcmQK # password
  PMA_USER: dXNlcgo= # user
  PMA_PASSWORD: cGFzc3dvcmQK # password
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
