apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-rolebinding
  namespace: default
subjects:
- kind: User
  name: husni
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io
