apiVersion: apps/v1
kind: Deployment
metadata:
  name: faulty-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faulty-app
  template:
    metadata:
      labels:
        app: faulty-app
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "echo No longer faulty! && sleep 3600"]
